{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "38e985de-a3e6-4a61-8a0a-ee02b7fe5a9c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Welcome to the Daily Calorie Tracker!\n",
      "This tool helps you record your meals and calculate your total calorie intake.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# -----------------------------------------------\n",
    "# Name:  Mohit Tanwar\n",
    "# Date: 10 Nov 2025\n",
    "# Project: Daily Calorie Tracker CLI\n",
    "# -----------------------------------------------\n",
    "\n",
    "print(\"Welcome to the Daily Calorie Tracker!\")\n",
    "print(\"This tool helps you record your meals and calculate your total calorie intake.\\n\")\n",
    "\n",
    "# -------------------------------\n",
    "# Task 2: Input & Data Collection\n",
    "# -------------------------------\n",
    "\n",
    "meal_names = []\n",
    "meal_calories = []\n",
    "\n",
    "num_meals = int(input(\"How many meals do you want to enter? \"))\n",
    "\n",
    "for i in range(num_meals):\n",
    "    print(f\"\\nMeal {i+1}:\")\n",
    "    meal = input(\"Enter meal name: \")\n",
    "    calories = float(input(\"Enter calories for this meal: \"))\n",
    "\n",
    "    meal_names.append(meal)\n",
    "    meal_calories.append(calories)\n",
    "\n",
    "# -------------------------------\n",
    "# Task 3: Calorie Calculations\n",
    "# -------------------------------\n",
    "\n",
    "total_calories = sum(meal_calories)\n",
    "average_calories = total_calories / num_meals\n",
    "\n",
    "daily_limit = float(input(\"\\nEnter your daily calorie limit: \"))\n",
    "\n",
    "# -------------------------------\n",
    "# Task 4: Warning \n",
    "# -------------------------------\n",
    "\n",
    "if total_calories > daily_limit:\n",
    "    limit_msg = \"⚠️ WARNING: You exceeded your daily calorie limit!\"\n",
    "else:\n",
    "    limit_msg = \"✔ You are within your daily calorie limit.\"\n",
    "\n",
    "# -------------------------------\n",
    "# Task 5: Neatly Formatted Output\n",
    "# -------------------------------\n",
    "\n",
    "print(\"\\n\\n----- DAILY CALORIE SUMMARY -----\")\n",
    "print(\"Meal Name\\tCalories\")\n",
    "print(\"----------------------------------\")\n",
    "\n",
    "for i in range(num_meals):\n",
    "    print(f\"{meal_names[i]}\\t\\t{meal_calories[i]}\")\n",
    "\n",
    "print(\"----------------------------------\")\n",
    "print(f\"Total:\\t\\t{total_calories}\")\n",
    "print(f\"Average:\\t{average_calories:.2f}\")\n",
    "print(\"----------------------------------\")\n",
    "print(limit_msg)\n",
    "\n",
    "# -------------------------------\n",
    "# Task 6: Bonus - Save to File\n",
    "# -------------------------------\n",
    "\n",
    "save = input(\"\\nDo you want to save this session log? (yes/no): \")\n",
    "\n",
    "if save.lower() == \"yes\":\n",
    "    import datetime\n",
    "    timestamp = datetime.datetime.now()\n",
    "\n",
    "    with open(\"calorie_log.txt\", \"w\") as file:\n",
    "        file.write(\"----- DAILY CALORIE SUMMARY -----\\n\")\n",
    "        file.write(f\"Timestamp: {timestamp}\\n\\n\")\n",
    "        file.write(\"Meal Name\\tCalories\\n\")\n",
    "        file.write(\"---------------------------------\\n\")\n",
    "\n",
    "        for i in range(num_meals):\n",
    "            file.write(f\"{meal_names[i]}\\t\\t{meal_calories[i]}\\n\")\n",
    "\n",
    "        file.write(\"---------------------------------\\n\")\n",
    "        file.write(f\"Total:\\t\\t{total_calories}\\n\")\n",
    "        file.write(f\"Average:\\t{average_calories:.2f}\\n\")\n",
    "        file.write(\"---------------------------------\\n\")\n",
    "        file.write(limit_msg + \"\\n\")\n",
    "\n",
    "    print(\"Session saved to calorie_log.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0128d7e2-6bf8-4dbd-bc86-aff01d83d40d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
